<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/13 20:20:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=TripleThread',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
