<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/08/13 20:20:51
return array(

  // ioMenuPlugin_module_libs

  // ioMenuPlugin_lib
  'iomenuadminitem' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioMenuPlugin/lib/admin/ioMenuAdminItem.class.php',
  'iomenu' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioMenuPlugin/lib/ioMenu.class.php',
  'iomenuitem' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioMenuPlugin/lib/ioMenuItem.class.php',

  // ioPagePlugin_module_libs

  // ioPagePlugin_lib
  'ioextendedpageactions' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/actions/ioExtendedPageActions.class.php',
  'iopageconfig' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/config/ioPageConfig.class.php',
  'iopagecontentloader' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/content/ioPageContentLoader.class.php',
  'pluginiopageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/filter/doctrine/PluginioPageFormFilter.class.php',
  'pluginiopageform' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/form/doctrine/PluginioPageForm.class.php',
  'pluginiopage' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/model/doctrine/PluginioPage.class.php',
  'pluginiopagetable' => '/Users/adamkimbrel/Sites/TripleThread/plugins/ioPagePlugin/lib/model/doctrine/PluginioPageTable.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Users/adamkimbrel/Sites/TripleThread/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'ttactions' => '/Users/adamkimbrel/Sites/TripleThread/lib/action/ttActions.class.php',
  'basettbasicpageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/base/BasettBasicPageFormFilter.class.php',
  'basettpageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/base/BasettPageFormFilter.class.php',
  'baseformfilterdoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'baseiopageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/ioPagePlugin/base/BaseioPageFormFilter.class.php',
  'iopageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/ioPagePlugin/ioPageFormFilter.class.php',
  'ttbasicpageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/ttBasicPageFormFilter.class.php',
  'ttpageformfilter' => '/Users/adamkimbrel/Sites/TripleThread/lib/filter/doctrine/ttPageFormFilter.class.php',
  'baseform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/BaseForm.class.php',
  'basettbasicpageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/base/BasettBasicPageForm.class.php',
  'basettpageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/base/BasettPageForm.class.php',
  'baseformdoctrine' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/BaseFormDoctrine.class.php',
  'baseiopageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/ioPagePlugin/base/BaseioPageForm.class.php',
  'iopageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/ioPagePlugin/ioPageForm.class.php',
  'ttbasicpageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/ttBasicPageForm.class.php',
  'ttpageform' => '/Users/adamkimbrel/Sites/TripleThread/lib/form/doctrine/ttPageForm.class.php',

  // project_model
  'basettbasicpage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/base/BasettBasicPage.class.php',
  'basettpage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/base/BasettPage.class.php',
  'baseiopage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ioPagePlugin/base/BaseioPage.class.php',
  'iopage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ioPagePlugin/ioPage.class.php',
  'iopagetable' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ioPagePlugin/ioPageTable.class.php',
  'ttbasicpage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ttBasicPage.class.php',
  'ttbasicpagetable' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ttBasicPageTable.class.php',
  'ttpage' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ttPage.class.php',
  'ttpagetable' => '/Users/adamkimbrel/Sites/TripleThread/lib/model/doctrine/ttPageTable.class.php',

  // application
  'myuser' => '/Users/adamkimbrel/Sites/TripleThread/apps/frontend/lib/myUser.class.php',

  // modules
);
