<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/08/13 20:20:51
sfConfig::add(array(
  'app_io_page_toolbar_partial' => 'ioPage/toolbar',
  'app_io_page_defaults' => array (
  'title_pattern' => '%title%',
  'keywords_pattern' => '%meta_keywords%',
  'description_pattern' => '%meta_description%',
  'content_loader' => 'ioPageContentLoader',
),
));
