<?php

/**
 * ttBasicPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ttBasicPageTable extends ioPageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ttBasicPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ttBasicPage');
    }
}