<?php

/**
 * BaseioPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $body
 * @property boolean $is_published
 * @property datetime $published_at
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $type
 * @property string $internal_slug
 * 
 * @method string   getTitle()            Returns the current record's "title" value
 * @method clob     getBody()             Returns the current record's "body" value
 * @method boolean  getIsPublished()      Returns the current record's "is_published" value
 * @method datetime getPublishedAt()      Returns the current record's "published_at" value
 * @method string   getMetaKeywords()     Returns the current record's "meta_keywords" value
 * @method string   getMetaDescription()  Returns the current record's "meta_description" value
 * @method string   getType()             Returns the current record's "type" value
 * @method string   getInternalSlug()     Returns the current record's "internal_slug" value
 * @method ioPage   setTitle()            Sets the current record's "title" value
 * @method ioPage   setBody()             Sets the current record's "body" value
 * @method ioPage   setIsPublished()      Sets the current record's "is_published" value
 * @method ioPage   setPublishedAt()      Sets the current record's "published_at" value
 * @method ioPage   setMetaKeywords()     Sets the current record's "meta_keywords" value
 * @method ioPage   setMetaDescription()  Sets the current record's "meta_description" value
 * @method ioPage   setType()             Sets the current record's "type" value
 * @method ioPage   setInternalSlug()     Sets the current record's "internal_slug" value
 * 
 * @package    TripleThread
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseioPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('io_page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('published_at', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('meta_keywords', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('meta_description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('internal_slug', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'ttPage' => 
             array(
              'type' => 'basic',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => false,
             'uniqueIndex' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}